# Generated by Django 3.0.7 on 2020-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Название поста блога', max_length=200, verbose_name='Название'),
        ),
    ]
