# Generated by Django 3.0.7 on 2020-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='default_title'),
            preserve_default=False,
        ),
    ]
